<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Praticien extends \App\Entity\Praticien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_nom', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_prenom', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_tel', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_mail', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_rue', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_codePostal', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_ville', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_coefNotoriete', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_visites', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'praticien_visiteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_nom', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_prenom', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_tel', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_mail', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_rue', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_codePostal', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_ville', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_coefNotoriete', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'pra_visites', '' . "\0" . 'App\\Entity\\Praticien' . "\0" . 'praticien_visiteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Praticien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPraNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraNom', []);

        return parent::getPraNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraNom(?string $pra_nom): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraNom', [$pra_nom]);

        return parent::setPraNom($pra_nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraPrenom', []);

        return parent::getPraPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraPrenom(?string $pra_prenom): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraPrenom', [$pra_prenom]);

        return parent::setPraPrenom($pra_prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraTel', []);

        return parent::getPraTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraTel(?string $pra_tel): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraTel', [$pra_tel]);

        return parent::setPraTel($pra_tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraMail', []);

        return parent::getPraMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraMail(?string $pra_mail): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraMail', [$pra_mail]);

        return parent::setPraMail($pra_mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraRue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraRue', []);

        return parent::getPraRue();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraRue(string $pra_rue): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraRue', [$pra_rue]);

        return parent::setPraRue($pra_rue);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraCodePostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraCodePostal', []);

        return parent::getPraCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraCodePostal(string $pra_codePostal): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraCodePostal', [$pra_codePostal]);

        return parent::setPraCodePostal($pra_codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraVille', []);

        return parent::getPraVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraVille(string $pra_ville): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraVille', [$pra_ville]);

        return parent::setPraVille($pra_ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraCoefNotoriete(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraCoefNotoriete', []);

        return parent::getPraCoefNotoriete();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraCoefNotoriete(int $pra_coefNotoriete): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraCoefNotoriete', [$pra_coefNotoriete]);

        return parent::setPraCoefNotoriete($pra_coefNotoriete);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraVisites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraVisites', []);

        return parent::getPraVisites();
    }

    /**
     * {@inheritDoc}
     */
    public function addPraVisite(\App\Entity\Visites $praVisite): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPraVisite', [$praVisite]);

        return parent::addPraVisite($praVisite);
    }

    /**
     * {@inheritDoc}
     */
    public function removePraVisite(\App\Entity\Visites $praVisite): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePraVisite', [$praVisite]);

        return parent::removePraVisite($praVisite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraticienVisiteur(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraticienVisiteur', []);

        return parent::getPraticienVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addPraticienVisiteur(\App\Entity\Visiteur $praticienVisiteur): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPraticienVisiteur', [$praticienVisiteur]);

        return parent::addPraticienVisiteur($praticienVisiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removePraticienVisiteur(\App\Entity\Visiteur $praticienVisiteur): \App\Entity\Praticien
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePraticienVisiteur', [$praticienVisiteur]);

        return parent::removePraticienVisiteur($praticienVisiteur);
    }

}
