<?php

namespace ContainerINRXxHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EKkdgH9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EKkdgH9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EKkdgH9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'motifRepository' => ['privates', 'App\\Repository\\MotifRepository', 'getMotifRepositoryService', true],
        ], [
            'motifRepository' => 'App\\Repository\\MotifRepository',
        ]);
    }
}
