<?php

namespace ContainerINRXxHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pp7Jii2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pp7Jii2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pp7Jii2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'visitesRepository' => ['privates', 'App\\Repository\\VisitesRepository', 'getVisitesRepositoryService', true],
        ], [
            'visitesRepository' => 'App\\Repository\\VisitesRepository',
        ]);
    }
}
