<?php

namespace ContainerINRXxHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3V1XBDiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3V1XBDi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3V1XBDi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'praticien' => ['privates', '.errored..service_locator.3V1XBDi.App\\Entity\\Praticien', NULL, 'Cannot autowire service ".service_locator.3V1XBDi": it references class "App\\Entity\\Praticien" but no such service exists.'],
        ], [
            'praticien' => 'App\\Entity\\Praticien',
        ]);
    }
}
