<?php

namespace ContainerINRXxHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PoIH8hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._PoIH8h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._PoIH8h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'motif' => ['privates', '.errored..service_locator._PoIH8h.App\\Entity\\Motif', NULL, 'Cannot autowire service ".service_locator._PoIH8h": it references class "App\\Entity\\Motif" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'motif' => 'App\\Entity\\Motif',
        ]);
    }
}
