<?php

namespace ContainerINRXxHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordEncoderSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\PasswordEncoderSubscriber' shared autowired service.
     *
     * @return \App\Events\PasswordEncoderSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'PasswordEncoderSubscriber.php';

        return $container->privates['App\\Events\\PasswordEncoderSubscriber'] = new \App\Events\PasswordEncoderSubscriber(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
