<?php

namespace ContainerJpOxVhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CxkOB8TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cxkOB8T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cxkOB8T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MotifController::delete' => ['privates', '.service_locator._PoIH8h', 'get_ServiceLocator_PoIH8hService', true],
            'App\\Controller\\MotifController::edit' => ['privates', '.service_locator._PoIH8h', 'get_ServiceLocator_PoIH8hService', true],
            'App\\Controller\\MotifController::index' => ['privates', '.service_locator.EKkdgH9', 'get_ServiceLocator_EKkdgH9Service', true],
            'App\\Controller\\MotifController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MotifController::show' => ['privates', '.service_locator.4HYA6Ga', 'get_ServiceLocator_4HYA6GaService', true],
            'App\\Controller\\PraticienController::delete' => ['privates', '.service_locator.G4gPDEg', 'get_ServiceLocator_G4gPDEgService', true],
            'App\\Controller\\PraticienController::edit' => ['privates', '.service_locator.G4gPDEg', 'get_ServiceLocator_G4gPDEgService', true],
            'App\\Controller\\PraticienController::index' => ['privates', '.service_locator.wh2V8A_', 'get_ServiceLocator_Wh2V8AService', true],
            'App\\Controller\\PraticienController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PraticienController::show' => ['privates', '.service_locator.3V1XBDi', 'get_ServiceLocator_3V1XBDiService', true],
            'App\\Controller\\VisitesController::delete' => ['privates', '.service_locator.7WsaDkb', 'get_ServiceLocator_7WsaDkbService', true],
            'App\\Controller\\VisitesController::edit' => ['privates', '.service_locator.7WsaDkb', 'get_ServiceLocator_7WsaDkbService', true],
            'App\\Controller\\VisitesController::index' => ['privates', '.service_locator.pp7Jii2', 'get_ServiceLocator_Pp7Jii2Service', true],
            'App\\Controller\\VisitesController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VisitesController::show' => ['privates', '.service_locator.yKz.mE2', 'get_ServiceLocator_YKz_ME2Service', true],
            'App\\Controller\\VisiteurController::delete' => ['privates', '.service_locator.L.ron..', 'get_ServiceLocator_L_Ron__Service', true],
            'App\\Controller\\VisiteurController::edit' => ['privates', '.service_locator.L.ron..', 'get_ServiceLocator_L_Ron__Service', true],
            'App\\Controller\\VisiteurController::index' => ['privates', '.service_locator.WxSBQHT', 'get_ServiceLocator_WxSBQHTService', true],
            'App\\Controller\\VisiteurController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VisiteurController::show' => ['privates', '.service_locator.Z7D4XtT', 'get_ServiceLocator_Z7D4XtTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\MotifController:delete' => ['privates', '.service_locator._PoIH8h', 'get_ServiceLocator_PoIH8hService', true],
            'App\\Controller\\MotifController:edit' => ['privates', '.service_locator._PoIH8h', 'get_ServiceLocator_PoIH8hService', true],
            'App\\Controller\\MotifController:index' => ['privates', '.service_locator.EKkdgH9', 'get_ServiceLocator_EKkdgH9Service', true],
            'App\\Controller\\MotifController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MotifController:show' => ['privates', '.service_locator.4HYA6Ga', 'get_ServiceLocator_4HYA6GaService', true],
            'App\\Controller\\PraticienController:delete' => ['privates', '.service_locator.G4gPDEg', 'get_ServiceLocator_G4gPDEgService', true],
            'App\\Controller\\PraticienController:edit' => ['privates', '.service_locator.G4gPDEg', 'get_ServiceLocator_G4gPDEgService', true],
            'App\\Controller\\PraticienController:index' => ['privates', '.service_locator.wh2V8A_', 'get_ServiceLocator_Wh2V8AService', true],
            'App\\Controller\\PraticienController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PraticienController:show' => ['privates', '.service_locator.3V1XBDi', 'get_ServiceLocator_3V1XBDiService', true],
            'App\\Controller\\VisitesController:delete' => ['privates', '.service_locator.7WsaDkb', 'get_ServiceLocator_7WsaDkbService', true],
            'App\\Controller\\VisitesController:edit' => ['privates', '.service_locator.7WsaDkb', 'get_ServiceLocator_7WsaDkbService', true],
            'App\\Controller\\VisitesController:index' => ['privates', '.service_locator.pp7Jii2', 'get_ServiceLocator_Pp7Jii2Service', true],
            'App\\Controller\\VisitesController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VisitesController:show' => ['privates', '.service_locator.yKz.mE2', 'get_ServiceLocator_YKz_ME2Service', true],
            'App\\Controller\\VisiteurController:delete' => ['privates', '.service_locator.L.ron..', 'get_ServiceLocator_L_Ron__Service', true],
            'App\\Controller\\VisiteurController:edit' => ['privates', '.service_locator.L.ron..', 'get_ServiceLocator_L_Ron__Service', true],
            'App\\Controller\\VisiteurController:index' => ['privates', '.service_locator.WxSBQHT', 'get_ServiceLocator_WxSBQHTService', true],
            'App\\Controller\\VisiteurController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VisiteurController:show' => ['privates', '.service_locator.Z7D4XtT', 'get_ServiceLocator_Z7D4XtTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\MotifController::delete' => '?',
            'App\\Controller\\MotifController::edit' => '?',
            'App\\Controller\\MotifController::index' => '?',
            'App\\Controller\\MotifController::new' => '?',
            'App\\Controller\\MotifController::show' => '?',
            'App\\Controller\\PraticienController::delete' => '?',
            'App\\Controller\\PraticienController::edit' => '?',
            'App\\Controller\\PraticienController::index' => '?',
            'App\\Controller\\PraticienController::new' => '?',
            'App\\Controller\\PraticienController::show' => '?',
            'App\\Controller\\VisitesController::delete' => '?',
            'App\\Controller\\VisitesController::edit' => '?',
            'App\\Controller\\VisitesController::index' => '?',
            'App\\Controller\\VisitesController::new' => '?',
            'App\\Controller\\VisitesController::show' => '?',
            'App\\Controller\\VisiteurController::delete' => '?',
            'App\\Controller\\VisiteurController::edit' => '?',
            'App\\Controller\\VisiteurController::index' => '?',
            'App\\Controller\\VisiteurController::new' => '?',
            'App\\Controller\\VisiteurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\MotifController:delete' => '?',
            'App\\Controller\\MotifController:edit' => '?',
            'App\\Controller\\MotifController:index' => '?',
            'App\\Controller\\MotifController:new' => '?',
            'App\\Controller\\MotifController:show' => '?',
            'App\\Controller\\PraticienController:delete' => '?',
            'App\\Controller\\PraticienController:edit' => '?',
            'App\\Controller\\PraticienController:index' => '?',
            'App\\Controller\\PraticienController:new' => '?',
            'App\\Controller\\PraticienController:show' => '?',
            'App\\Controller\\VisitesController:delete' => '?',
            'App\\Controller\\VisitesController:edit' => '?',
            'App\\Controller\\VisitesController:index' => '?',
            'App\\Controller\\VisitesController:new' => '?',
            'App\\Controller\\VisitesController:show' => '?',
            'App\\Controller\\VisiteurController:delete' => '?',
            'App\\Controller\\VisiteurController:edit' => '?',
            'App\\Controller\\VisiteurController:index' => '?',
            'App\\Controller\\VisiteurController:new' => '?',
            'App\\Controller\\VisiteurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
