<?php

namespace ContainerJpOxVhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotif2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._PoIH8h.App\Entity\Motif' shared service.
     *
     * @return \App\Entity\Motif
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._PoIH8h": it references class "App\\Entity\\Motif" but no such service exists.');
    }
}
