<?php

namespace ContainerJpOxVhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPraticien2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G4gPDEg.App\Entity\Praticien' shared service.
     *
     * @return \App\Entity\Praticien
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.G4gPDEg": it references class "App\\Entity\\Praticien" but no such service exists.');
    }
}
