<?php

namespace ContainerJpOxVhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisites2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yKz.mE2.App\Entity\Visites' shared service.
     *
     * @return \App\Entity\Visites
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yKz.mE2": it references class "App\\Entity\\Visites" but no such service exists.');
    }
}
