<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerINRXxHf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerINRXxHf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerINRXxHf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerINRXxHf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerINRXxHf\App_KernelDevDebugContainer([
    'container.build_hash' => 'INRXxHf',
    'container.build_id' => '43d06dac',
    'container.build_time' => 1648562358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerINRXxHf');
