<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJpOxVhp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJpOxVhp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJpOxVhp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJpOxVhp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJpOxVhp\App_KernelDevDebugContainer([
    'container.build_hash' => 'JpOxVhp',
    'container.build_id' => 'c8b84438',
    'container.build_time' => 1648738163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJpOxVhp');
